# Generated by Django 3.2.22 on 2023-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
